language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r install/requirements.txt"
# Specify MySql depencdency
services:
  - mysql
# setup
before_script:
  - mysql -uroot -e 'create database energyathome;'
# command to run tests
script: nosetests
