language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install python-serial python-mysqldb
  - pip install python-mysqldb
# command to run tests
script: nosetests
